packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  '@parcel/watcher': true
  vue-demi: true
  sharp: true
  workerd: true
  unrs-resolver: false
  better-sqlite3: true

linkWorkspacePackages: true
preferWorkspacePackages: true
autoInstallPeers: true

overrides:
  h3: 1.15.11
